#!/usr/bin/env bash

set -e
set -o pipefail

distributions=(jazzy rolling)

for distro in "${distributions[@]}"; do
  destDir=
  rosPackages="(import ./default.nix).outputs.legacyPackages.x86_64-linux.$distro.rosPackages"
  pkgNames=(
    zenoh-cpp-vendor
  )
  for pkgName in "${pkgNames[@]}"; do
    hash=$(nurl -e "$rosPackages.$pkgName.cargoDeps.vendorStaging")
    mkdir -p "ros-packages/overrides/$distro/cargo-hashes"
    printf '# Generated by update.bash\n"%s"' "$hash" > "ros-packages/overrides/$distro/cargo-hashes/$pkgName.nix"
  done
done
