distributions = ["jazzy", "rolling"]
out_dir = "ros-packages/generated"
max_concurrent_downloads = 16

[env.humble]
PAL_DISTRO = ""
RMF_ENABLE_FAILOVER = ""
BUILD_WITH_LDMRS_SUPPORT = ""
GZ_VERSION = "fortress"
IGNITION_VERSION = "fortress"

[env.iron]
RMF_ENABLE_FAILOVER = ""
BUILD_WITH_LDMRS_SUPPORT = ""
GZ_VERSION = "fortress"
IGNITION_VERSION = "fortress"

[env.jazzy]
GZ_BUILD_FROM_SOURCE = "1"
RMF_ENABLE_FAILOVER = ""
BUILD_WITH_LDMRS_SUPPORT = ""
GZ_VERSION = "harmonic"
IGNITION_VERSION = "harmonic"

[env.rolling]
GZ_BUILD_FROM_SOURCE = "1"
RMF_ENABLE_FAILOVER = ""
BUILD_WITH_LDMRS_SUPPORT = ""
GZ_VERSION = "harmonic"
IGNITION_VERSION = "harmonic"
DISABLE_GROUPS_WORKAROUND = "1"

[auto_patching]
ignore_files = ['test', 'example', 'ci-build\.cmake']
ignore_urls = [
  'fast-dds\.docs\.eprosima\.com',
  '^https://github\.com/.*?/.*?/archive/refs/heads/.*$',
  '^https://raw\.githubusercontent\.com/.*?/.*?/(master|main)/.*$',
  '^https://librealsense\.intel\.com/Releases/connectivity_check$',
  '^http://downloads\.tuxfamily\.org/eigen/lapack_addons_3\.4\.1\.tgz$',
]
replace_urls = [
  { from = '^https://git\.savannah\.gnu\.org/git/freetype/freetype2\.git$', to = "https://gitlab.freedesktop.org/freetype/freetype.git" },
  { from = '^https://download\.savannah\.gnu\.org/releases/freetype/freetype-([0-9]+)\.([0-9]+)\.([0-9]+)\.tar\.gz', to = 'https://gitlab.freedesktop.org/freetype/freetype/-/archive/VER-$1-$2-$3/freetype-VER-$1-$2-$3.tar.gz' },
]
