distributions = ["jazzy", "rolling"]
out_dir = "ros-packages/generated"
max_concurrent_downloads = 16
buildtool_packages = ["ament_lint_common"]
runtime_packages = [
  "rmw",
  "ros2test",
  "ros2run",
  "launch_testing",
  "rmf_building_map_tools",
  "rosidl_typesupport_interface",
  "qt5-qmake",
  "rcutils",
  "ament_index_python",
  "gz_math_vendor",
]
runtime_groups = [
  "rosidl_interface_packages",
  "rosidl_typesupport_cpp_packages",
  "rosidl_typesupport_c_packages",
  "rosidl_runtime_packages",
  "rmw_implementation_packages",
]
hybrid_packages = ["python3", "gtest"]

[env.humble]
PAL_DISTRO = ""
RMF_ENABLE_FAILOVER = ""
BUILD_WITH_LDMRS_SUPPORT = ""
GZ_VERSION = "fortress"
IGNITION_VERSION = "fortress"

[env.iron]
RMF_ENABLE_FAILOVER = ""
BUILD_WITH_LDMRS_SUPPORT = ""
GZ_VERSION = "fortress"
IGNITION_VERSION = "fortress"

[env.jazzy]
GZ_BUILD_FROM_SOURCE = "1"
RMF_ENABLE_FAILOVER = ""
BUILD_WITH_LDMRS_SUPPORT = ""
GZ_VERSION = "harmonic"
IGNITION_VERSION = "harmonic"

[env.rolling]
GZ_BUILD_FROM_SOURCE = "1"
RMF_ENABLE_FAILOVER = ""
BUILD_WITH_LDMRS_SUPPORT = ""
GZ_VERSION = "harmonic"
IGNITION_VERSION = "harmonic"
DISABLE_GROUPS_WORKAROUND = "1"

[auto_patching]
ignore_files = ['test', 'example', 'ci-build\.cmake']
ignore_urls = [
  'fast-dds\.docs\.eprosima\.com',
  '^https://github\.com/.*?/.*?/archive/refs/heads/.*$',
  '^https://raw\.githubusercontent\.com/.*?/.*?/(master|main)/.*$',
  '^https://librealsense\.intel\.com/Releases/connectivity_check$',
]
