name: Build

on:
  pull_request:
    types:
      - "opened"
      - "synchronize"
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        distro:
          - jazzy
    runs-on: ubuntu-latest
    environment: 
      name: cache
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v13
        with:
          extra-conf: |
            substituters = https://cache.nixos.org https://cache.garnix.io https://rosnix.cachix.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g= rosnix.cachix.org-1:jY+HaQHRBBXJKhFVNdB2jg4+7ohjH6lUAFXhUAawh6k=
      - name: Build
        run: nix run .#ci-build "${{ matrix.distro }}"

