name: Build

on:
  pull_request:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        distro:
          - jazzy
    runs-on: ubuntu-latest
    environment: 
      name: build
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v13
        with:
          extra-conf: |
            substituters = https://cache.garnix.io
            trusted-public-keys = cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g=
      - name: Build
        run: nix run .#ci-build "${{ matrix.distro }}"

