name: Crate Sync Pull-request

on:
  push:
    branches:
    - develop
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

jobs:
  create-sync-pr:
    runs-on: ubuntu-latest
    environment: 
      name: maintenance
    steps:
      - uses: actions/checkout@v4
        with:
          ref: develop
          fetch-depth: 0
      - id: create_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Create Pull Request
        run: |
          export GH_TOKEN='${{ steps.create_token.outputs.token }}'
          if ! git log --exit-code origin/main..develop> /dev/null; then
            pr_url="$(gh pr list --base main --head develop --state open --json url --jq .[].url)"
            if [[ -n $pr_url ]]; then
              echo "PR already exists -> ${pr_url}"
              exit 0
            else
              echo "Creating PR"
              gh pr create --base main --title "Merge develop branch into main" --body ""
              echo "Enabling auto-merge"
              gh pr merge --auto --merge
            fi
          else
            echo "main branch is already up to date."
          fi

